### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by nazhendenb** [ERYhua/nyaHentaiCrawler#1]
root@VM-0-9-ubuntu:~/nyaHentaiCrawler/src/main/java/com/cn/main# javac nyaPictureMain.java 
nyaPictureMain.java:3: error: package com.cn.util does not exist
import com.cn.util.HttpClientUtil;
                  ^
nyaPictureMain.java:4: error: package org.apache.commons.io does not exist
import org.apache.commons.io.FileUtils;
                            ^
nyaPictureMain.java:5: error: package org.apache.http does not exist
import org.apache.http.HttpEntity;
                      ^
nyaPictureMain.java:6: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.CloseableHttpResponse;
                                     ^
nyaPictureMain.java:7: error: package org.apache.http.client.methods does not exist
import org.apache.http.client.methods.HttpGet;
                                     ^
nyaPictureMain.java:8: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.CloseableHttpClient;
                                  ^
nyaPictureMain.java:9: error: package org.apache.http.impl.client does not exist
import org.apache.http.impl.client.HttpClients;
                                  ^
nyaPictureMain.java:10: error: package org.jsoup does not exist
import org.jsoup.Jsoup;
                ^
nyaPictureMain.java:11: error: package org.jsoup.nodes does not exist
import org.jsoup.nodes.Document;
                      ^
nyaPictureMain.java:12: error: package org.jsoup.nodes does not exist
import org.jsoup.nodes.Element;
                      ^
nyaPictureMain.java:13: error: package org.jsoup.select does not exist
import org.jsoup.select.Elements;
                       ^
nyaPictureMain.java:54: error: cannot find symbol
                CloseableHttpClient httpClient = HttpClients.createDefault(); // 创建HttpClient实例
                ^
  symbol:   class CloseableHttpClient
  location: class nyaPictureMain
nyaPictureMain.java:54: error: cannot find symbol
                CloseableHttpClient httpClient = HttpClients.createDefault(); // 创建HttpClient实例
                                                 ^
  symbol:   variable HttpClients
  location: class nyaPictureMain
nyaPictureMain.java:55: error: cannot find symbol
                HttpGet httpGet = new HttpGet(fileUrl+i+suffix); // 创建Httpget实例
                ^
  symbol:   class HttpGet
  location: class nyaPictureMain
nyaPictureMain.java:55: error: cannot find symbol
                HttpGet httpGet = new HttpGet(fileUrl+i+suffix); // 创建Httpget实例
                                      ^
  symbol:   class HttpGet
  location: class nyaPictureMain
nyaPictureMain.java:58: error: cannot find symbol
                CloseableHttpResponse response = null;
                ^
  symbol:   class CloseableHttpResponse
  location: class nyaPictureMain
nyaPictureMain.java:60: error: cannot find symbol
                HttpEntity entity = response.getEntity(); // 获取返回实体
                ^
  symbol:   class HttpEntity
  location: class nyaPictureMain
nyaPictureMain.java:64: error: cannot find symbol
                    FileUtils.copyInputStreamToFile(inputStream, new File(intputFile+i+suffix));//引用org.apache.commons.io.FileUtils
                    ^
  symbol:   variable FileUtils
  location: class nyaPictureMain
nyaPictureMain.java:84: error: cannot find symbol
                html = HttpClientUtil.getSource(url);
                       ^
  symbol:   variable HttpClientUtil
  location: class nyaPictureMain
nyaPictureMain.java:86: error: cannot find symbol
                Document document = Jsoup.parse(html);
                ^
  symbol:   class Document
  location: class nyaPictureMain
nyaPictureMain.java:86: error: cannot find symbol
                Document document = Jsoup.parse(html);
                                    ^
  symbol:   variable Jsoup
  location: class nyaPictureMain
nyaPictureMain.java:87: error: cannot find symbol
                Element element = document.selectFirst("div.container").selectFirst("a");
                ^
  symbol:   class Element
  location: class nyaPictureMain
nyaPictureMain.java:95: error: cannot find symbol
                Elements picSum = document.select("div.thumb-container");
                ^
  symbol:   class Elements
  location: class nyaPictureMain
23 errors

完全不懂java，百度查运行.java文件要用javac命令编译，结果试着编译了一下就报错。  请问大佬的脚本对javac版本有要求吗？

**Comment by ERYhua** [comment]
啊这.jpg
现在这个源站更换了几回地址爬虫项目也没在维护了，如果感兴趣可以自己学习爬取下

**Comment by nazhendenb** [comment]
> 啊这.jpg
> 现在这个源站更换了几回地址爬虫项目也没在维护了，如果感兴趣可以自己学习爬取下
好吧   谢谢大佬
